class User(object):
    """Data class for a Tinycards user entity.

    Args:
        creation_date (int): Timestamp of when the user's account was created.
        email (string): Email address the user's account is registered to.
        fullname (string): The full name of the user.
        id (int): The user ID generated by Tinycards/Duolingo.
        learning_language (str): Language code of the language the user has
            be learning last (e.g., 'fr' for French).
        picture (str): Link to the user's profile picture.
        subscribed (bool): ??
        subscriber_count (int): Number of other users that have subscribed to
            the current user.
        subscription_count (int): Number of other users the current user has
            subscribed to.
        ui_language (str): Language code of the language the user has selected
            for the Tinycards user interface (e.g., 'en' for English).
        username (str): The user's unique username used by Tinycards/Duolingo.
    """
    creation_date: int
    email: str
    fullname: str
    id: int
    learning_language: str
    picture: str
    subscribed: bool
    subscriber_count: int
    subscription_count: int
    ui_language: str
    username: str
